name: Bug Report
description: Something isn't working as expected
labels: [bug]
body:
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      multiple: true
      options: [Android, iOS, macOS, Windows, Linux, Web, Go Server]
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened vs. what you expected
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: "1. ...\n2. ...\n3. ..."
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs / stack trace
      render: shell
